apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "espresso.fullname" . }}-config
  labels:
    {{- include "espresso.labels" . | nindent 4 }}
data:
  ESPRESSO_TENANT: {{ .Values.espresso.tenant | quote }}
  ESPRESSO_INTERFACE: {{ .Values.espresso.interface | quote }}

  DB_TYPE: {{ .Values.db.type | quote }}
  POSTGRES_HOST: {{ .Values.db.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.db.postgres.port | quote }}
  POSTGRES_DATABASE: {{ .Values.db.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.db.postgres.user | quote }}
  POSTGRES_SSLMODE: {{ .Values.db.postgres.sslMode | quote }}

  TEMPORAL_HOST: {{ .Values.temporal.host | quote }}
  TEMPORAL_PORT: {{ .Values.temporal.port | quote }}

  ESPRESSO_UI_API_HOST: espresso-backend
  ESPRESSO_UI_API_PORT: "8088"


{{- if eq .Values.espresso.interface "AZSB" }}
  BROKER_HOST: {{ required "azsb.host is required when espresso.interface=AZSB" .Values.azsb.host | quote }}
  BROKER_USER: {{ required "azsb.user is required when espresso.interface=AZSB" .Values.azsb.user | quote }}
  BROKER_TOPIC_ORDER: {{ required "azsb.topic.order is required when espresso.interface=AZSB" .Values.azsb.topic.order | quote }}
  BROKER_QUEUE_DELIVERY: {{ required "azsb.queue.delivery is required when espresso.interface=AZSB" .Values.azsb.queue.delivery | quote }}
  BROKER_QUEUE_RECEIPT: {{ required "azsb.queue.receipt is required when espresso.interface=AZSB" .Values.azsb.queue.receipt | quote }}
{{- end }}

{{- if .Values.espresso.sso.enabled }}
  AUTHORITY_URL: {{ required "espresso.sso.authorityUrl is required when espresso.sso.enabled=true" .Values.espresso.sso.authorityUrl | quote }}
  AUTHORITY_CLIENT_ID: {{ required "espresso.sso.clientId is required when espresso.sso.enabled=true" .Values.espresso.sso.clientId | quote }}
  AUTHORITY_CLIENT_REDIRECT_URI: {{ required "espresso.sso.redirectUri is required when espresso.sso.enabled=true" .Values.espresso.sso.redirectUri | quote }}
  AUTHORITY_CLIENT_POST_LOGOUT_REDIRECT_URI: {{ required "espresso.sso.postLogoutRedirectUri is required when espresso.sso.enabled=true" .Values.espresso.sso.postLogoutRedirectUri | quote }}
  AUTHORITY_CLIENT_SCOPE: {{ .Values.espresso.sso.scope | default "openid profile email" | quote }}
{{- end }}
