{{- if and .Values.ingress.enabled (eq .Values.espresso.interface "REST") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: espresso-api
  labels:
    {{- include "espresso.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /rest/v1
            pathType: Prefix
            backend:
              service:
                name: espresso-rest-gateway
                port:
                  number: 80

          - path: /rest/v2
            pathType: Prefix
            backend:
              service:
                name: espresso-rest-gateway
                port:
                  number: 80
{{- end }}
